version: '3.8'
services:
  server:
    build: .
    ports:
      - '3000:3000'
    env_file:
    - ./server/.env
    depends_on:
      - redis
  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
